### ISSUE TITLE
Almond crashes on issuing wake word.

### ISSUE THREAD

**Issue by mostlychris** [stanford-oval/almond-hassio-repository#12]
Almond starts up, speaks the "...how can I help you" line and then waits. When I issue the wake word, Almond crashes with the following error.

I am running the following version:

Current version: edge-7c75cfe
The home server version of Almond 2.0 (edge builds).

```
/opt/almond/main.js:24
process.on('unhandledRejection', (up) => { throw up; });
                                           ^
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Ocp-Apim-Subscription-Key"
    at ClientRequest.setHeader (_http_outgoing.js:533:3)
    at new ClientRequest (_http_client.js:242:14)
    at Object.request (https.js:316:10)
    at /opt/almond/node_modules/genie-toolkit/dist/lib/speech/speech_recognizer.js:251:29
    at new Promise (<anonymous>)
    at SpeechRecognizer._obtainAccessToken (/opt/almond/node_modules/genie-toolkit/dist/lib/speech/speech_recognizer.js:250:16)
    at SpeechRecognizer._ensureAccessToken (/opt/almond/node_modules/genie-toolkit/dist/lib/speech/speech_recognizer.js:269:21)
    at SpeechRecognizer._ensureConnection (/opt/almond/node_modules/genie-toolkit/dist/lib/speech/speech_recognizer.js:345:25)
    at SpeechRecognizer.request (/opt/almond/node_modules/genie-toolkit/dist/lib/speech/speech_recognizer.js:349:14)
    at SpeechHandler._onDetected (/opt/almond/node_modules/genie-toolkit/dist/lib/speech/speech_handler.js:199:49)
Emitted 'error' event on SpeechHandler instance at:
    at SpeechRecognizer.<anonymous> (/opt/almond/node_modules/genie-toolkit/dist/lib/speech/speech_handler.js:76:18)
    at SpeechRecognizer.emit (events.js:314:20)
    at /opt/almond/node_modules/genie-toolkit/dist/lib/speech/speech_recognizer.js:353:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}
```

**Comment by gcampax** [comment]
Thanks for the report. The particular build you tried is unfortunately broken because of a half finished change in how we talk to the speech tp text server. A new build is on its way which should solve the issue. Can you confirm?

**Comment by mostlychris** [comment]
Figured that might be it. I'll let you know as soon as the update appears and I can install it.

**Comment by mostlychris** [comment]
The update I applied today is working well. The error is not present.

**Comment by gcampax** [comment]
Awesome, thanks for testing!
